name: Deployment exercise 1
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: lint
              run: npm run lint
            - name: test code
              run: npm run test
            - name: build test
              run: npm run build
            - name: deploy code
              run: echo "deploying..."

  